identifier: l9k620ccz1e319z8
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: seo
homeFolder: /home/asplap3275/Desktop/Workspace/seo
distFolder: dist/seo
outDir: /home/asplap3275/Desktop/Workspace/seo/dist/static
handle404: ''
allowErrorCollect: true
